"""Initial migration

Revision ID: 79f6ce373ad9
Revises: 
Create Date: 2025-07-29 02:56:15.396430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f6ce373ad9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('saved_party_ids', sa.String(), nullable=False, server_default="[]"))
    op.execute("UPDATE user SET saved_party_ids = '[]' WHERE saved_party_ids IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'saved_party_ids')
    # ### end Alembic commands ###
