"""add_current_party_id_and_media_url

Revision ID: a103a4a0f751
Revises: 467b827f4d53
Create Date: 2025-09-15 19:49:56.549960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a103a4a0f751'
down_revision: Union[str, Sequence[str], None] = '467b827f4d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('current_party_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_party_id')
    op.drop_column('party', 'media_url')
    # ### end Alembic commands ###
