"""remove_custom_claims_field

Revision ID: e3b646493c91
Revises: a103a4a0f751
Create Date: 2025-09-15 19:52:44.559227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b646493c91'
down_revision: Union[str, Sequence[str], None] = 'a103a4a0f751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'custom_claims')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('custom_claims', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
